---
# tasks file for nagios_ubuntu
- name: Install packages for nagios
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php7.4
      - libgd-dev
    state: latest
    update_cache: yes

- name: Stop firewall
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Download and unarchive nagios core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create make file
  shell: cd /tmp/nagioscore-nagios-4.4.5; sh /tmp/nagioscore-nagios-4.4.5/configure --with-httpd-conf=/etc/apache2/sites-enabled
  register: make_file
    # when: nagios_source.changed

- name: Compile from source
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: all
  become: yes
    # when: make_file.changed

- name: Create user and group
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-groups-users
  become: yes
    # when: make_file.changed

- name: Add www-data user to nagios group
  user:
    name: www-data
    groups: nagios
    append: yes

- name: Install binaries
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install
  become: yes
    # when: make_file.changed

- name: Install service
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-daemoninit
  become: yes
    # when: make_file.changed

- name: Install command mode
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-commandmode
  become: yes
    # when: make_file.changed

- name: Install configuration files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-config
  become: yes
    # when: make_file.changed

- name: Install apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-webconf
  become: yes
    # when: make_file.changed
  register: install_webconf

- name: Enable rewrite module
  apache2_module:
    state: present
    name: rewrite

- name: Enable cgi module
  apache2_module:
    state: present
    name: cgi

- name: Start and enable nagios
  service:
    name: nagios
    state: started
    enabled: yes
  # when: install_webconf.changed
